In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import kerr
import numpy as np
import matplotlib.pyplot as plt

In [3]:
U = np.arange(-6, 6, 1)
delta = 28*U
gam = 0.1*U
eta = 0.1*U

f = 1/(U - eta*(1j))
g = 1/(U - eta*(1j))
c = (delta + (1j*gam)/2.)/(U - eta*(1j))

/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  
/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys
/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys
/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide
  


In [4]:
f, g, c

(array([-0.16501650-0.01650165j, -0.19801980-0.01980198j,
        -0.24752475-0.02475248j, -0.33003300-0.0330033j ,
        -0.49504950-0.04950495j, -0.99009901-0.0990099j ,
                inf       +nanj,  0.99009901+0.0990099j ,
         0.49504950+0.04950495j,  0.33003300+0.0330033j ,
         0.24752475+0.02475248j,  0.19801980+0.01980198j]),
 array([-0.16501650-0.01650165j, -0.19801980-0.01980198j,
        -0.24752475-0.02475248j, -0.33003300-0.0330033j ,
        -0.49504950-0.04950495j, -0.99009901-0.0990099j ,
                inf       +nanj,  0.99009901+0.0990099j ,
         0.49504950+0.04950495j,  0.33003300+0.0330033j ,
         0.24752475+0.02475248j,  0.19801980+0.01980198j]),
 array([ 27.71782178+2.82178218j,  27.71782178+2.82178218j,
         27.71782178+2.82178218j,  27.71782178+2.82178218j,
         27.71782178+2.82178218j,  27.71782178+2.82178218j,
                 nan       +nanj,  27.71782178+2.82178218j,
         27.71782178+2.82178218j,  27.71782178+2.82178218j,


In [5]:
system = kerr.Kerr(f[0], g[0], c[0])

In [6]:
print("Normalization", system.normalization())

Normalization 1.01190474292


In [7]:
x = y = np.arange(-6, 6, 0.1)

In [8]:
X, Y = np.meshgrid(x, y)
Z = system.wigner(X+(1j)*Y)

In [9]:
print("Wigner plot for f = {} \n g = {} \n c = {}".format(f[0], g[0], c[0]))
plt.contour(X, Y, Z)
plt.title("Wigner plot")
plt.ylabel("Real(z)")
plt.xlabel("Imag(z)")
plt.grid()
plt.colorbar()
plt.show()

Wigner plot for f = (-0.16501650165016502-0.016501650165016504j) 
 g = (-0.16501650165016502-0.016501650165016504j) 
 c = (27.717821782178216+2.8217821782178225j)
